# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("DriverAnalyzer"))
        MainWindow.resize(1280, 800)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.thread1_bn = QtGui.QPushButton(self.centralwidget)
        self.thread1_bn.setObjectName(_fromUtf8("thread1_bn"))
        self.horizontalLayout_2.addWidget(self.thread1_bn)
        self.thread2_bn = QtGui.QPushButton(self.centralwidget)
        self.thread2_bn.setObjectName(_fromUtf8("thread2_bn"))
        self.horizontalLayout_2.addWidget(self.thread2_bn)
        self.thread3_bn = QtGui.QPushButton(self.centralwidget)
        self.thread3_bn.setObjectName(_fromUtf8("thread3_bn"))
        self.horizontalLayout_2.addWidget(self.thread3_bn)
        self.thread4_bn = QtGui.QPushButton(self.centralwidget)
        self.thread4_bn.setObjectName(_fromUtf8("thread4_bn"))
        self.horizontalLayout_2.addWidget(self.thread4_bn)
        self.thread5_bn = QtGui.QPushButton(self.centralwidget)
        self.thread5_bn.setObjectName(_fromUtf8("thread5_bn"))
        self.horizontalLayout_2.addWidget(self.thread5_bn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.banner = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.banner.setFont(font)
        self.banner.setTextFormat(QtCore.Qt.RichText)
        self.banner.setAlignment(QtCore.Qt.AlignCenter)
        self.banner.setWordWrap(True)
        self.banner.setIndent(10)
        self.banner.setObjectName(_fromUtf8("banner"))
        self.verticalLayout_4.addWidget(self.banner)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_4.addWidget(self.line_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.play_bn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_bn.sizePolicy().hasHeightForWidth())
        self.play_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.play_bn.setFont(font)
        self.play_bn.setObjectName(_fromUtf8("play_bn"))
        self.verticalLayout.addWidget(self.play_bn)

        self.pause_bn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_bn.sizePolicy().hasHeightForWidth())
        self.pause_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pause_bn.setFont(font)
        self.pause_bn.setObjectName(_fromUtf8("pause_bn"))
        self.verticalLayout.addWidget(self.pause_bn)

        self.record_bn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.record_bn.sizePolicy().hasHeightForWidth())
        self.record_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.record_bn.setFont(font)
        self.record_bn.setObjectName(_fromUtf8("record_bn"))
        self.verticalLayout.addWidget(self.record_bn)
        self.empty_bn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.empty_bn.sizePolicy().hasHeightForWidth())
        self.empty_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.empty_bn.setFont(font)
        self.empty_bn.setObjectName(_fromUtf8("empty_bn"))
        self.verticalLayout.addWidget(self.empty_bn)
        self.setting_bn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setting_bn.sizePolicy().hasHeightForWidth())
        self.setting_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.setting_bn.setFont(font)
        self.setting_bn.setObjectName(_fromUtf8("setting_bn"))
        self.verticalLayout.addWidget(self.setting_bn)
        self.exit_bn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_bn.sizePolicy().hasHeightForWidth())
        self.exit_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.exit_bn.setFont(font)
        self.exit_bn.setObjectName(_fromUtf8("exit_bn"))
        self.verticalLayout.addWidget(self.exit_bn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout.addWidget(self.line_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))

        self.main_video_layout = QtGui.QVBoxLayout()
        self.main_video_layout.setObjectName(_fromUtf8("main_video_layout"))
        self.horizontalLayout_5.addLayout(self.main_video_layout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.model1_bn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model1_bn.sizePolicy().hasHeightForWidth())
        self.model1_bn.setSizePolicy(sizePolicy)
        self.model1_bn.setText(_fromUtf8(""))
        self.model1_bn.setObjectName(_fromUtf8("model1_bn"))
        self.verticalLayout_2.addWidget(self.model1_bn)
        self.model2_bn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model2_bn.sizePolicy().hasHeightForWidth())
        self.model2_bn.setSizePolicy(sizePolicy)
        self.model2_bn.setText(_fromUtf8(""))
        self.model2_bn.setObjectName(_fromUtf8("model2_bn"))
        self.verticalLayout_2.addWidget(self.model2_bn)
        self.model3_bn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model3_bn.sizePolicy().hasHeightForWidth())
        self.model3_bn.setSizePolicy(sizePolicy)
        self.model3_bn.setText(_fromUtf8(""))
        self.model3_bn.setObjectName(_fromUtf8("model3_bn"))
        self.verticalLayout_2.addWidget(self.model3_bn)
        self.model4_bn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model4_bn.sizePolicy().hasHeightForWidth())
        self.model4_bn.setSizePolicy(sizePolicy)
        self.model4_bn.setText(_fromUtf8(""))
        self.model4_bn.setObjectName(_fromUtf8("model4_bn"))
        self.verticalLayout_2.addWidget(self.model4_bn)
        self.model5_bn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model5_bn.sizePolicy().hasHeightForWidth())
        self.model5_bn.setSizePolicy(sizePolicy)
        self.model5_bn.setText(_fromUtf8(""))
        self.model5_bn.setObjectName(_fromUtf8("model5_bn"))
        self.verticalLayout_2.addWidget(self.model5_bn)
        self.info_display = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_display.sizePolicy().hasHeightForWidth())
        self.info_display.setSizePolicy(sizePolicy)
        self.info_display.setReadOnly(True)
        self.info_display.setObjectName(_fromUtf8("info_display"))
        self.verticalLayout_2.addWidget(self.info_display)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5.setStretch(0, 10)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(2, 10)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 9)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.setStretch(4, 10)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_5.addWidget(self.line_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.banner.setText(_translate("MainWindow", "PriVision System", None))
